name: Docs
on: push
permissions:
  contents: read
  pages: write
  id-token: write
concurrency:
  group: Docs
  cancel-in-progress: true
jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"
          cache: "yarn"

      - run: yarn list

  # docs:
  #   environment:
  #     name: github-pages
  #     url: ${{ steps.deployment.outputs.page_url }}
  #   runs-on: ubuntu-latest
  #   if: github.ref == 'refs/heads/master'
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v3
  #     - name: Configure pages
  #       uses: actions/configure-pages@v2
  #     - name: Install
  #       run: yarn install
  #     - name: Build site
  #       run: yarn build:docs
  #     - name: Upload artifact
  #       if: github.ref == 'refs/heads/main'
  #       uses: actions/upload-pages-artifact@v1
  #       with:
  #         path: site
  #     - name: Deploy pages
  #       if: github.ref == 'refs/heads/main'
  #       id: deployment
  #       uses: actions/deploy-pages@v1
